### PR TITLE
Don't box value in `Fragile<T>`

### PR DESCRIPTION
**Pull request by Noratrieb**
I'm not sure why the boxing was done here, but it isn't required for soundness and not doing it is more efficient so I've removed it. Maybe there's a good reason for doing it that I haven't considered.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I'm in favor of this change. I wanted to do this change before but I wasn't too comfortable with the behavior of `SemiSticky`. It's unclear if that type even makes too much sense, but if that change does happen it probably should `Box` there for the fragile case.

**Comment by mitsuhiko** [comment]
I'm actually not entirely sure about the change now. Today `Fragile<T>` boxes internally and in turn accomplishes that `Drop` is a noop for a lot of types. In the future `Fragile<Box<T>>` would invoke the dtor even in cases where it's not necessary because `mem::needs_drop::<Box<T>>()` would always return `true`. This severely limits the usefulness of `Fragile` as all drops in another thread for boxed values would abort the process.

**Comment by Nilstrieb** [comment]
People can just use `Box<Fragile<T>>` couldn't they?

**Comment by mitsuhiko** [comment]
I'm actually wondering now if this does not mean there is a memory leak in `Fragile` now for values without dtor. I need to validate this.

**Pull request merged**
